server:
  port: 8086
spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qualitydb?useSSL=false&serverTimezone=UTC
    username: root
    password: 123

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 实体扫描，多个 package 用逗号或者分号分隔
  typeAliasesPackage: com.example.demo.entity
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID", 2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    # 字段策略 0:"忽略判断", 1:"非 NULL 判断", 2:"非空判断"
    field-strategy: 1
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新 mapper 调试神器
    refresh-mapper: true
    # 逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    # springboot 项目 mybatis plus 设置 jdbcTypeForNull (oracle 数据库需配置 JdbcType.NULL, 默认是 Other)
    jdbc-type-for-null: 'null'